
# Name of Website
name: Joshua Key

# Markdown Type
markdown: kramdown

# Pagination
paginate: 3
paginate_path: "/blog/page:num/"


# permalink: /Blog/:year/:month/:day/:title
theme: jekyll-theme-cayman