port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, LICENSE.txt]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Joshua Key - Portfolio"
keywords:    "Joshua, Key, JoshuaKey, Game, GameDev, Development, Portfolio, SinglePaged, jekyll, template, github, blog"
description: "A Personal Portfolio site for Joshua Key"
source_link: "https://github.com/JoshuaKey/JoshuaKey.github.io"
favicon:     "img/favicon.ico"
# touch_icon:  
# google_analytics_key: 


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  lightblue: '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false